version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
    user: ${POSTGRES_USERNAME_PROD}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      dockerfile: Dockerfile-dev
    command: npm run start:dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_USERNAME_PROD: ${POSTGRES_USERNAME_PROD}
      POSTGRES_PASSWORD_PROD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DATABASE_PROD: ${POSTGRES_DATABASE_PROD}
      POSTGRES_HOST_PROD: ${POSTGRES_HOST_PROD}
    volumes:
      - .:/usr/multisig-service/
      - /usr/multisig-service/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
