version: '3.6'
services:
  web:
    build:
      dockerfile: Dockerfile-prod
    command: npm run start
    logging:
      driver: "gcplogs"
      options:
        max-size: 10m
        max-file: "3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/usr/multisig-service/
      - /usr/multisig-service/node_modules
    ports:
      - "8000:8000"
